# how to get a token for your discord "server": https://github.com/reactiflux/discord-irc/wiki/Creating-a-discord-bot-&-getting-a-token
discord_token: <redacted>
irc_server: irc.freenode.net:6697
no_tls: false # this requires restart
guild_id: 748871194572226661
nickserv_identify: koo7
channel_mappings:
  "#frdcsa": 748871194572226666
  "#logicmoo": 753342836346454106
#  "#posi": 752244695668752424 this does not work, only one discord channel is relayed
suffix: "[d]"
irc_listener_name: "[d]"
webirc_pass: <nickserv password, redacted>
#insecure: true # this requires restart
debug: true
webhook_prefix: "(auto-test)" # this probably requires restart
webhook_limit: 3
#simple: true # this requires restart
